"""baseline schema

Revision ID: 0d2e742e66ef
Revises: 
Create Date: 2026-06-21 15:49:38.886495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2e742e66ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('endpoints_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blackboard',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('json_blob', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('draw_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('scene_slug', sa.String(), nullable=False),
    sa.Column('origin_proposal_turn', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('done_image_id', sa.Integer(), nullable=True),
    sa.Column('draft_messages', sa.Text(), nullable=False),
    sa.Column('draft_prompt', sa.Text(), nullable=False),
    sa.Column('draft_manifest', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_proposals_story_id'), 'draw_proposals', ['story_id'], unique=False)
    op.create_table('image_gens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('scene_slug', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('final_prompt', sa.Text(), nullable=False),
    sa.Column('ref_asset_ids', sa.Text(), nullable=False),
    sa.Column('ref_image_paths', sa.Text(), nullable=False),
    sa.Column('output_path', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('source_turn', sa.Integer(), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_gens_story_id'), 'image_gens', ['story_id'], unique=False)
    op.create_table('knowledge',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('newapi_accounts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('newapi_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reference_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_assets_story_id'), 'reference_assets', ['story_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_owner_id'), 'stories', ['owner_id'], unique=False)
    op.create_table('story_settings',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('default_model', sa.String(), nullable=False),
    sa.Column('director_a_model', sa.String(), nullable=False),
    sa.Column('writer_model', sa.String(), nullable=False),
    sa.Column('director_b_model', sa.String(), nullable=False),
    sa.Column('options_model', sa.String(), nullable=False),
    sa.Column('illustrator_model', sa.String(), nullable=False),
    sa.Column('style_bible', sa.Text(), nullable=False),
    sa.Column('visual_style_bible', sa.Text(), nullable=False),
    sa.Column('image_model', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('beat_title', sa.String(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('director_a_json', sa.Text(), nullable=False),
    sa.Column('director_b_json', sa.Text(), nullable=False),
    sa.Column('blackboard_after', sa.Text(), nullable=False),
    sa.Column('director_a_messages', sa.Text(), nullable=False),
    sa.Column('writer_messages', sa.Text(), nullable=False),
    sa.Column('director_b_messages', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('options_messages', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_story_id'), 'turns', ['story_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_turns_story_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_table('story_settings')
    op.drop_index(op.f('ix_stories_owner_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_reference_assets_story_id'), table_name='reference_assets')
    op.drop_table('reference_assets')
    op.drop_table('newapi_accounts')
    op.drop_table('knowledge')
    op.drop_index(op.f('ix_image_gens_story_id'), table_name='image_gens')
    op.drop_table('image_gens')
    op.drop_index(op.f('ix_draw_proposals_story_id'), table_name='draw_proposals')
    op.drop_table('draw_proposals')
    op.drop_table('blackboard')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
